var oTable = null;
$(document).ready(function () {
    Metronic.init(); // init metronic core componets
    Layout.init(); // init layout
    QuickSidebar.init(); // init quick sidebar
    $.extend(true, $.fn.DataTable.TableTools.classes, {
        "container": "btn-group tabletools-btn-group pull-right",
        "buttons": {
            "normal": "btn btn-sm default",
            "disabled": "btn btn-sm default disabled"
        }
    });
    oTable = $('#customer_table').dataTable({
        stateSave: true,
        "searching": false,
        "ordering": false,
        "processing": true,
        "serverSide": true,
        "deferRender": true,
        "ajax": API_SERVER + "joker/api/cust/get_all/",
        "columns": [
            {"data": "id"},
            {"data": "age"},
            {"data": "gender"},
            {"data": "yrs_w_club"},
            {
                "data": "is_member",
                "render": function (data, type, full, meta) {
                    return data ? "Yes" : "No";
                }
            },
            {
                "data": "is_hrs_owner",
                "render": function (data, type, full, meta) {
                    return data ? "Yes" : "No";
                }
            },
            {"data": "major_channel"},
            {"data": "mtg_num"},
            {"data": "inv"},
            {"data": "div"},
            {"data": "rr"},
            {"data": "end_bal"},
            {"data": "recharge_times"},
            {"data": "recharge_amount"},
            {"data": "withdraw_times"},
            {"data": "withdraw_amount"}
        ],
        "dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable
        "tableTools": {
            "sSwfPath": "assets/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf",
            "aButtons": [{
                "sExtends": "pdf",
                "sButtonText": "PDF"
            }, {
                "sExtends": "csv",
                "sButtonText": "CSV"
            }, {
                "sExtends": "xls",
                "sButtonText": "Excel"
            }, {
                "sExtends": "print",
                "sButtonText": "Print",
                "sInfo": 'Please press "CTRL+P" to print or "ESC" to quit',
                "sMessage": "Generated by DataTables"
            }, {
                "sExtends": "copy",
                "sButtonText": "Copy"
            }]
        }
    });
    $('#customer_table_wrapper').find('.dataTables_length select').select2();
});
