var oTable = null;
$(document).ready(function () {
    Metronic.init(); // init metronic core componets
    Layout.init(); // init layout
    QuickSidebar.init(); // init quick sidebar
    $.extend(true, $.fn.DataTable.TableTools.classes, {
        "container": "btn-group tabletools-btn-group pull-right",
        "buttons": {
            "normal": "btn btn-sm default",
            "disabled": "btn btn-sm default disabled"
        }
    });
    oTable = $('#customer_table').DataTable({
        stateSave: true,
        "searching": false,
        "ordering": false,
        "processing": true,
        "serverSide": true,
        "deferRender": true,
        "ajax": API_SERVER + "joker/api/cust/get_all/",
        "columns": [
            {"data": "id"},
            {"data": "age"},
            {"data": "gender"},
            {"data": "yrs_w_club"},
            {
                "data": "is_member",
                "render": function (data, type, full, meta) {
                    return data ? "Yes" : "No";
                }
            },
            {
                "data": "is_hrs_owner",
                "render": function (data, type, full, meta) {
                    return data ? "Yes" : "No";
                }
            },
            {"data": "major_channel"},
            {"data": "mtg_num"},
            {"data": "inv"},
            {"data": "div"},
            {"data": "rr"},
            {"data": "end_bal"},
            {"data": "recharge_times"},
            {"data": "recharge_amount"},
            {"data": "withdraw_times"},
            {"data": "withdraw_amount"},
            {
                "data": "prediction",
                "render": function (data, type, full, meta) {
                    var prefix = "<span class='label bg-red'>";
                    var postfix = " %</span>";
                    var r = find_prediction_type(data, "Grow");
                    if (r != null) return prefix + (r.prob * 100.0).toFixed(1) + postfix;
                    else return "-";
                }
            },
            {
                "data": "prediction",
                "render": function (data, type, full, meta) {
                    var prefix = "<span class='label bg-green'>";
                    var postfix = " %</span>";
                    var r = find_prediction_type(data, "Lapse");
                    if (r != null) return prefix + (r.prob * 100.0).toFixed(1) + postfix;
                    else return "-";
                }
            }
        ],
        "dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable
        "tableTools": {
            "sSwfPath": "assets/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf",
            "aButtons": [{
                "sExtends": "pdf",
                "sButtonText": "PDF"
            }, {
                "sExtends": "csv",
                "sButtonText": "CSV"
            }, {
                "sExtends": "xls",
                "sButtonText": "Excel"
            }, {
                "sExtends": "print",
                "sButtonText": "Print",
                "sInfo": 'Please press "CTRL+P" to print or "ESC" to quit',
                "sMessage": "Generated by DataTables"
            }, {
                "sExtends": "copy",
                "sButtonText": "Copy"
            }]
        }
    });
    $('#customer_table_wrapper').find('.dataTables_length select').select2();
    $('#customer_table tbody').on('click', 'tr', function () {
        var data = oTable.row(this).data();
        var html = "<div>";
        html += "<span class='label bg-" + interpret_gender_color(data.gender) + "'>" + interpret_gender_name(data.gender) + "</span> ";
        html += "<span class='label bg-" + (data.is_member ? "green" : "grey") + "'>" + (data.is_member ? "Member" : "Non-Member") + "</span> ";
        html += "<span class='label bg-" + (data.is_hrs_owner ? "yellow" : "grey") + "'>" + (data.is_hrs_owner ? "Horse Owner" : "Not Horse Owner") + "</span> ";
        html += "</div><hr/><div class='row'>";
        html += "<div class='col-md-5'>";
        var pred = find_prediction_type(data.prediction, "Grow");
        if (pred == null) pred = {
            prob: "-",
            reason_code_1: "N/A",
            reason_code_2: "N/A",
            reason_code_3: "N/A"
        };
        html += "<span class='bold font-red'><i class='fa fa-arrow-up'></i> Propensity to Grow: </span>" + (pred.prob * 100.0).toFixed(1) + " %<br/>";
        html += "<span class='bold'><i class='fa'></i> Reason Code: </span><ul>";
        html += "<li>" + pred.reason_code_1 + "</li>";
        html += "<li>" + pred.reason_code_2 + "</li>";
        html += "<li>" + pred.reason_code_3 + "</li>";
        html += "</ul>";
        pred = find_prediction_type(data.prediction, "Lapse");
        if (pred == null) pred = {
            prob: "-",
            reason_code_1: "N/A",
            reason_code_2: "N/A",
            reason_code_3: "N/A"
        };
        html += "<span class='bold font-green'><i class='fa fa-arrow-down'></i> Propensity to Lapse: </span>" + (pred.prob * 100.0).toFixed(1) + " %<br/>";
        html += "<span class='bold'><i class='fa'></i> Reason Code: </span><ul>";
        html += "<li>" + pred.reason_code_1 + "</li>";
        html += "<li>" + pred.reason_code_2 + "</li>";
        html += "<li>" + pred.reason_code_3 + "</li>";
        html += "</ul>";
        html += "</div>";
        html += "<div class='col-md-7'>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Age: </span>" + data.age + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Club Years: </span>" + data.yrs_w_club + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Major Channel: </span>" + data.major_channel + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Meetings Attended in Last Season: </span>" + data.mtg_num + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Total Investment: </span>" + data.inv + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Total Investment in Beginning of Season: </span>" + data.inv_seg_1 + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Total Investment in Middle of Season: </span>" + data.inv_seg_2 + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Total Investment in Ending of Season: </span>" + data.inv_seg_3 + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Dividend: </span>" + data.div + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Recovery Rate: </span>" + data.rr + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Balance: </span>" + data.end_bal + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Recharge Times: </span>" + data.recharge_times + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Recharge Amount: </span>" + data.recharge_amount + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Withdraw Times: </span>" + data.withdraw_times + "<br/>";
        html += "<span class='bold font-blue-madison'><i class='fa fa-angle-right'></i> Withdraw Amount: </span>" + data.withdraw_amount;
        html += "</div></div>";
        bootbox.dialog({
            message: html,
            title: "CUST_ID: " + data.id
        });
    });
});
